### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by sbkim052** [tarepan/UniversalVocoding#2]
Hi @tarepan , thank you for sharing your git.
did you train the model in the audio samples(https://tarepan.github.io/UniversalVocoding/) only  with a single Japanese speaker dataset?

**Comment by tarepan** [comment]
Yes, trained with only JSUT (1 female JP speaker 10 hours).

**Comment by sbkim052** [comment]
wow
it is interesting that your model is robust even though it is only trained on a single speaker
